name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
         - uses: actions/checkout@v3
         - name: "docker login"
           run: docker login -u="ashisparida" -p="7381284169"
         - name: Build the Docker image
           run: docker build . --file Dockerfile --tag ashisparida/todaytask:$GITHUB_tm
         - name: docker push
           run: docker push ashisparida/todaytask:$GITHUB_tm
      
